-- T-216: turn `payouts` into a real ledger of money the platform owes photographers.
--
-- Until now the only writer was `createPayoutFromTransfer`, which inserts a row
-- ALREADY in status 'paid' after a Stripe transfer succeeded. The three paths
-- where the transfer could NOT be sent (Connect account not active, net below
-- Stripe's 50-cent minimum, transfer threw) did nothing but `console.warn` —
-- no row, no queue, no retry. A photographer who sold and then finished Connect
-- onboarding never got that money, and nothing in the system knew it was owed.
--
-- This migration adds the columns that make a debt recordable and retryable, and
-- makes the row itself the concurrency primitive: the row is inserted BEFORE the
-- Stripe call and its id is the Stripe idempotency key, so the unique index below
-- PREVENTS a second payment instead of merely deduplicating the log of one.
--
-- Rollback is inert: reverting the code leaves these columns unread and any
-- outstanding rows unpaid — which is exactly the pre-T-216 behaviour, minus the
-- fact that the debt is now on the record. No down-migration.

-- ── New ledger columns ──────────────────────────────────────────────────────
alter table public.payouts
  add column if not exists stripe_charge_id text,
  add column if not exists currency text,
  add column if not exists hold_reason text,
  add column if not exists order_id uuid,
  add column if not exists order_kind text,
  add column if not exists transfer_batch_id uuid;

comment on column public.payouts.stripe_charge_id is
  'T-216: the Stripe charge this payout draws from. Together with photographer_id it is the exactly-once key (see the partial unique index below), and it is passed as `source_transaction` so Stripe itself refuses to over-draw the charge. NULL on rows predating T-216.';

comment on column public.payouts.currency is
  'T-216: the originating order''s currency. Transfers must match their source charge''s currency (a pre-T-193 charge settles in USD), so batching groups on (photographer, currency) and never merges the two.';

comment on column public.payouts.hold_reason is
  'T-216: why this payout could not be sent immediately — connect_inactive | below_minimum | transfer_failed. NOT NULL is what marks a row as ledger-managed: the retry worker only ever considers rows with BOTH this and stripe_charge_id set, so rows predating T-216 can never be wired to real money.';

comment on column public.payouts.order_id is
  'T-216: the order this payout came from, for tracing only. Deliberately NO foreign key: a guest sale lives in `guest_orders`, a different table, so an FK to `orders` would reject half the rows. Never used as an identity key — a payment intent whose first charge fails and second succeeds yields two charges for one order.';

comment on column public.payouts.order_kind is
  'T-216: which table order_id points at — order | guest_order.';

comment on column public.payouts.transfer_batch_id is
  'T-216: groups the sub-50-cent rows that were aggregated into one source-less transfer. Generated by the claiming UPDATE and read back from its RETURNING, never by the caller — an Inngest replay that minted a fresh uuid would produce a fresh idempotency key and re-transfer rows already in flight.';

alter table public.payouts drop constraint if exists payouts_order_kind_check;
alter table public.payouts
  add constraint payouts_order_kind_check
  check (order_kind is null or order_kind in ('order', 'guest_order'));

-- ── 'processing' status ─────────────────────────────────────────────────────
-- The state between "row claimed" and "transfer confirmed". A row sits here
-- while a Stripe call is in flight; the retry worker re-drives it with the SAME
-- idempotency key, which is why the worker must never revert a claim.
alter table public.payouts drop constraint if exists payouts_status_check;
alter table public.payouts
  add constraint payouts_status_check
  check (status in ('pending', 'approved', 'processing', 'paid', 'cancelled'));

-- ── Replace the uniqueness guarantee ────────────────────────────────────────
-- `stripe_transfer_id UNIQUE` (20260501000000) has to go: one aggregated
-- transfer now settles several sub-minimum rows, so N rows legitimately share a
-- transfer id. Dropped by name, with a lookup by definition as a fallback in
-- case the remote-schema dump renamed it.
do $$
declare
  conname_found text;
begin
  select con.conname into conname_found
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where nsp.nspname = 'public'
    and rel.relname = 'payouts'
    and con.contype = 'u'
    and (
      select array_agg(att.attname::text order by att.attname::text)
      from unnest(con.conkey) as k(attnum)
      join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k.attnum
    ) = array['stripe_transfer_id']::text[]
  limit 1;

  if conname_found is not null then
    execute format('alter table public.payouts drop constraint %I', conname_found);
  end if;
end
$$;
-- NOTE: `idx_payouts_stripe_transfer_id` (a plain partial index, same migration)
-- is deliberately KEPT — it serves the lookup, not the constraint.

-- The real exactly-once key. Partial so the rows predating T-216 (no charge id)
-- don't all collide on NULL.
create unique index if not exists payouts_charge_photographer_key
  on public.payouts (stripe_charge_id, photographer_id)
  where stripe_charge_id is not null;

comment on index public.payouts_charge_photographer_key is
  'T-216: one payout per (charge, photographer). Because the row is inserted BEFORE the Stripe transfer, a 23505 here means "another writer already owns this money" and the loser must transfer nothing — this is what stops a webhook redelivered past Stripe''s 24h idempotency window from paying the same sale twice.';

-- Hot query for the retry worker's sweep.
create index if not exists payouts_payable_holds_idx
  on public.payouts (photographer_id, currency)
  where status = 'pending' and hold_reason is not null;

-- ── Quarantine rows that predate the ledger ─────────────────────────────────
-- The self-INSERT RLS policy dropped below has been live since 2025, and the
-- (unused) `createPayout` wrote 'pending' rows with no charge and no reason.
-- Once a worker pays 'pending' rows those would become real money. The worker's
-- filter (`hold_reason is not null and stripe_charge_id is not null`) already
-- excludes them structurally; this stamp puts the intent on the record so the
-- rows can be told apart during any future audit.
update public.payouts
set admin_notes = coalesce(admin_notes || ' | ', '') ||
  'T-216: predates the payout ledger; not payable by the retry worker.'
where status = 'pending'
  and hold_reason is null
  and stripe_charge_id is null;

-- ── RLS: photographer-read, service-role-write ──────────────────────────────
-- T-216 is what converts these two policies from harmless to dangerous, so it
-- owns removing them. 'pending' now means "a background worker will really send
-- this money", which makes a self-inserted row straightforward theft, and a
-- photographer-cancelled hold unpayable forever (the unique index above then
-- blocks creating a replacement row for that charge).
--
-- Nothing user-facing regresses: `createPayout` has no caller in `src/` — only
-- test/integration/queries/payouts.test.ts, which uses the service role.
-- The SELECT policy stays, so the table does not become an
-- `rls_enabled_no_policy` advisor finding.
drop policy if exists "Photographers can create their own payouts" on public.payouts;
drop policy if exists "Photographers can cancel their own pending payouts" on public.payouts;

comment on table public.payouts is
  'T-216: ledger of photographer payouts. Service-role write only; photographers read their own. A row is created BEFORE its Stripe transfer and its id is the transfer''s idempotency key.';
